name: Deploy React to Github Pages

on: 
    push: 
        branches: 
            - main


permissions: 
    contents: read
    pages: write
    id-token: write


jobs:
    build-and-deploy:
        runs_on: ubuntu-latest

        steps:
            - name: Checkout repository
            uses: actions/checkout@v4
            
            - name: Setup Node.JS
            uses: actions/setup-node@v4
            with: npm i
                node-version: 22
                cache: npm

            - name: Install dependescies
            run: npm ci

            - name: Build project
            run: npm run build

            - name: Deploy to GitHub Pages
            uses: Jameslves/github-pages-deploy-action@v4
            with: 
                branche: gh-pages
                folder: dist